# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7272f6ed3ab3e1eae683d6fd00c1d583f0f2bf727d6a063c2990098deb58d75f58754cecc4a91beef2b0db5234857b9f2e42d11355be94551b82fb828ffa402f

test:
  secret_key_base: 4f0cc66dd3ca2320a702032cc3bd9d6587947c320020116253775c78038bbbf7b3cab9731d9e89e0adfbb24a8e9baf7ba326241d9e5a75785e15670d41a11f6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
